# Generated by Django - Empty migration for TernoAI integration
# Tables already exist from TernoAI's migrations, so no operations needed.

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = []  # Empty - tables already exist from TernoAI
