# Generated by Django 5.1.1 on 2026-01-08 01:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('django_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(default='Datasource 1', max_length=40)),
                ('type', models.CharField(choices=[('generic', 'Generic'), ('oracle', 'Oracle'), ('mysql', 'MySQL'), ('postgres', 'Postgres'), ('bigquery', 'BigQuery'), ('databricks', 'DataBricks'), ('snowflake', 'Snowflake')], default='generic', max_length=20)),
                ('is_erp', models.BooleanField(default=False, help_text='Flag to indicate if the datasource is an ERP system.')),
                ('connection_str', models.TextField(help_text='Connection string for the datasource', max_length=1000)),
                ('connection_json', models.JSONField(blank=True, help_text='JSON key file contents for authentication', null=True)),
                ('description', models.TextField(blank=True, default='', help_text='Give description of your datasource/schema.', max_length=1024, null=True)),
                ('enabled', models.BooleanField(default=True)),
                ('dialect_name', models.CharField(blank=True, default='', help_text='Auto-generated on save', max_length=20, null=True)),
                ('dialect_version', models.CharField(blank=True, default='', help_text='Auto-generated on save', max_length=20, null=True)),
            ],
            options={
                'db_table': 'terno_datasource',
            },
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('public_name', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
                ('complete_description', models.BooleanField(default=False, help_text='Denotes if description is generated for the table and all its columns.')),
                ('category', models.CharField(blank=True, max_length=255, null=True)),
                ('sample_rows', models.JSONField(blank=True, null=True)),
                ('description_updated_at', models.DateTimeField(blank=True, null=True)),
                ('data_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_app.datasource')),
            ],
            options={
                'db_table': 'terno_table',
            },
        ),
        migrations.CreateModel(
            name='PrivateTableSelector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_app.datasource')),
                ('tables', models.ManyToManyField(blank=True, related_name='private_tables', to='django_app.table')),
            ],
            options={
                'db_table': 'terno_privatetableselector',
            },
        ),
        migrations.CreateModel(
            name='GroupTableSelector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.group')),
                ('exclude_tables', models.ManyToManyField(blank=True, related_name='exclude_tables', to='django_app.table')),
                ('tables', models.ManyToManyField(blank=True, related_name='include_tables', to='django_app.table')),
            ],
            options={
                'db_table': 'terno_grouptableselector',
            },
        ),
        migrations.CreateModel(
            name='GroupTableRowFilter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filter_str', models.CharField(max_length=300)),
                ('data_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_app.datasource')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.group')),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_app.table')),
            ],
            options={
                'db_table': 'terno_grouptablerowfilter',
            },
        ),
        migrations.CreateModel(
            name='TableColumn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('public_name', models.CharField(blank=True, max_length=255, null=True)),
                ('data_type', models.CharField(blank=True, max_length=50)),
                ('description', models.CharField(blank=True, max_length=300, null=True)),
                ('unique_categories', models.JSONField(blank=True, default=dict, null=True)),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_app.table')),
            ],
            options={
                'db_table': 'terno_tablecolumn',
            },
        ),
        migrations.CreateModel(
            name='PrivateColumnSelector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_app.datasource')),
                ('columns', models.ManyToManyField(blank=True, related_name='private_columns', to='django_app.tablecolumn')),
            ],
            options={
                'db_table': 'terno_privatecolumnselector',
            },
        ),
        migrations.CreateModel(
            name='GroupColumnSelector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.group')),
                ('columns', models.ManyToManyField(blank=True, related_name='include_columns', to='django_app.tablecolumn')),
                ('exclude_columns', models.ManyToManyField(blank=True, related_name='exclude_columns', to='django_app.tablecolumn')),
            ],
            options={
                'db_table': 'terno_groupcolumnselector',
            },
        ),
        migrations.CreateModel(
            name='ForeignKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referred_schema', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='django_app.datasource')),
                ('constrained_table', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contrained_table', to='django_app.table')),
                ('referred_table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referred_table', to='django_app.table')),
                ('constrained_columns', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contrained_columns', to='django_app.tablecolumn')),
                ('referred_columns', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referred_columns', to='django_app.tablecolumn')),
            ],
            options={
                'db_table': 'terno_foreignkey',
            },
        ),
        migrations.CreateModel(
            name='TableRowFilter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filter_str', models.CharField(max_length=300)),
                ('data_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_app.datasource')),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_app.table')),
            ],
            options={
                'db_table': 'terno_tablerowfilter',
            },
        ),
        migrations.AddConstraint(
            model_name='table',
            constraint=models.UniqueConstraint(condition=models.Q(('public_name__isnull', True), _negated=True), fields=('data_source', 'public_name'), name='unique_table_public_name_per_datasource'),
        ),
        migrations.AddConstraint(
            model_name='tablecolumn',
            constraint=models.UniqueConstraint(condition=models.Q(('public_name__isnull', True), _negated=True), fields=('table', 'public_name'), name='unique_column_public_name_per_table'),
        ),
    ]
