# Generated by Django 5.1.1 on 2026-03-12 13:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('core', '0008_datasource_is_global'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupDataSourceSelector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datasources', models.ManyToManyField(blank=True, related_name='include_datasources', to='core.datasource')),
                ('exclude_datasources', models.ManyToManyField(blank=True, related_name='exclude_datasources', to='core.datasource')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.group')),
            ],
            options={
                'db_table': 'terno_groupdatasourceselector',
            },
        ),
        migrations.CreateModel(
            name='PrivateDataSourceSelector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datasources', models.ManyToManyField(blank=True, related_name='private_datasources', to='core.datasource')),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.coreorganisation')),
            ],
            options={
                'db_table': 'terno_privatedatasourceselector',
            },
        ),
    ]
