# Generated by Django 5.1.1 on 2026-04-13 03:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_servicetoken_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisationuser',
            name='active_token',
            field=models.ForeignKey(blank=True, help_text='Active sandbox ServiceToken for this user+org pair', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='org_users', to='core.servicetoken'),
        ),
        migrations.AddField(
            model_name='organisationuser',
            name='encrypted_token_key',
            field=models.BinaryField(blank=True, help_text='Fernet-encrypted raw key for the active sandbox token', null=True),
        ),
    ]
