# Generated by Django 5.1.1 on 2026-04-05 12:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_servicetoken_groups'),
    ]

    operations = [
        migrations.CreateModel(
            name='LLMConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('llm_type', models.CharField(choices=[('openai', 'OpenAI'), ('gemini', 'Gemini'), ('anthropic', 'Anthropic'), ('ollama', 'Ollama'), ('custom', 'CustomLLM'), ('terno', 'TernoLLM')], max_length=64)),
                ('api_key', models.CharField(max_length=512)),
                ('model_name', models.CharField(blank=True, max_length=256, null=True)),
                ('temperature', models.FloatField(blank=True, null=True)),
                ('custom_system_message', models.TextField(blank=True, null=True)),
                ('max_tokens', models.IntegerField(blank=True, null=True)),
                ('top_p', models.FloatField(blank=True, null=True)),
                ('top_k', models.FloatField(blank=True, null=True)),
                ('custom_parameters', models.JSONField(blank=True, null=True)),
                ('enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='llm_configs', to='core.coreorganisation')),
            ],
            options={
                'db_table': 'dbi_llm_configuration',
            },
        ),
    ]
