# Generated by Django 5.1.1 on 2026-04-17 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_promptexample'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promptexample',
            name='key',
            field=models.CharField(help_text='The key or variable name used in the prompt template.', max_length=255),
        ),
        migrations.AlterField(
            model_name='promptexample',
            name='value',
            field=models.TextField(help_text='The example value corresponding to the key.'),
        ),
    ]
