# Generated by Django 5.1.1 on 2026-05-05 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_organisationuser_active_token_and_more'),
        ('core', '0013_alter_promptexample_key_alter_promptexample_value'),
    ]

    operations = [
    ]
