# Generated by Django 5.1.1 on 2026-05-28 08:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_datasource_connection_json_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promptexample',
            name='example_type',
        ),
        migrations.AddField(
            model_name='promptexample',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='Owner of this memory. NULL = org-level shared knowledge.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prompt_examples', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='promptexample',
            name='is_shared',
            field=models.BooleanField(default=False, help_text='If True, this memory is visible to all users in the organisation. Only org admins can set this.'),
        ),
        migrations.AlterField(
            model_name='promptexample',
            name='key',
            field=models.CharField(help_text='The question or query key used for semantic matching.', max_length=255),
        ),
        migrations.AlterField(
            model_name='promptexample',
            name='value',
            field=models.TextField(help_text='The domain knowledge, business rule, or contextual answer.'),
        ),
    ]
