# Generated by Django 5.1.1 on 2026-07-05 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('core', '0016_remove_promptexample_example_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisationuser',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='Per-org roles/capabilities for this user+org membership', related_name='org_user_memberships', to='auth.group'),
        ),
    ]
