# Generated by Django 5.1.1 on 2026-06-09 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_remove_promptexample_example_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='notes',
            field=models.TextField(blank=True, help_text='Internal notes for this table.', null=True),
        ),
    ]
