# Generated by Django 5.2.12 on 2026-07-15 07:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_organisationuser_groups'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Memory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store', models.CharField(choices=[('user', 'User (private to creator)'), ('org', 'Organisation (shared)')], default='user', help_text='user = private to creator; org = shared across the organisation.', max_length=10)),
                ('name', models.SlugField(help_text="kebab-case slug, unique within its scope; the lookup key, e.g. 'zydus-active-users-join'.", max_length=100)),
                ('description', models.CharField(help_text='One-line hook shown in the memory index.', max_length=255)),
                ('memory_type', models.CharField(choices=[('user', 'User'), ('feedback', 'Feedback'), ('project', 'Project'), ('reference', 'Reference')], default='project', max_length=20)),
                ('content', models.TextField(help_text='The full fact body (plus Why/How-to-apply for feedback/project).')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='The author of this memory (always set at creation). Null only if that user was later deleted.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='memories', to=settings.AUTH_USER_MODEL)),
                ('data_source', models.ForeignKey(blank=True, help_text="scope axis: NULL = global (applies to any datasource); set = specific to this datasource's schema/rules.", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='memories', to='core.datasource')),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memories', to='core.coreorganisation')),
            ],
            options={
                'verbose_name': 'Memory',
                'verbose_name_plural': 'Memories',
                'db_table': 'terno_memory',
                'indexes': [models.Index(fields=['organisation', 'store', 'data_source'], name='terno_memor_organis_f9e103_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('store', 'org')), fields=('organisation', 'data_source', 'name'), name='uniq_org_memory_scope_name'), models.UniqueConstraint(condition=models.Q(('store', 'user')), fields=('organisation', 'created_by', 'data_source', 'name'), name='uniq_user_memory_scope_name')],
            },
        ),
    ]
