# Generated by Django 5.1.1 on 2026-06-22 11:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_dbiguide'),
    ]

    operations = [
        migrations.CreateModel(
            name='DBGuide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(help_text='Generated markdown guide')),
                ('generated_at', models.DateTimeField(auto_now=True)),
                ('generated_by', models.CharField(default='llm', max_length=100)),
                ('metadata_snapshot_at', models.DateTimeField(blank=True, help_text='When datasource metadata was used to generate this guide', null=True)),
                ('is_stale', models.BooleanField(default=False, help_text='True when datasource metadata changed after guide generation')),
                ('datasource', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='db_guide', to='core.datasource')),
            ],
            options={
                'db_table': 'terno_dbguide',
            },
        ),
        migrations.DeleteModel(
            name='DBIGuide',
        ),
    ]
