# Generated by Django 5.2.12 on 2026-07-17 13:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_memory'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='servicetoken',
            name='created_for',
            field=models.ForeignKey(blank=True, help_text='Whose identity this token acts as — the memory author for user-store writes, and what visibility is scoped to. This, not created_by, is what authorization reads.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tokens_created_for', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='servicetoken',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='Audit only: who/what actually minted this token (an admin, the system, etc). Not used for authorization.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_tokens', to=settings.AUTH_USER_MODEL),
        ),
    ]
