# Generated by Django 5.2.12 on 2026-07-17 13:07
# Backfill created_for on existing tokens. Before this split, created_by was
# overloaded to mean "whose identity this token acts as" in the CLI and

from django.db import migrations
from django.db.models import F


def backfill_created_for(apps, schema_editor):
    ServiceToken = apps.get_model('core', 'ServiceToken')
    ServiceToken.objects.filter(
        created_for__isnull=True, created_by__isnull=False
    ).update(created_for=F('created_by'))


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_servicetoken_created_for'),
    ]

    operations = [
        migrations.RunPython(backfill_created_for, noop_reverse),
    ]
