# Generated by Django 5.1.1 on 2026-07-20 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_backfill_created_for'),
    ]

    operations = [
        migrations.AddField(
            model_name='coreorganisation',
            name='org_prompt',
            field=models.TextField(blank=True, default='', help_text='Custom text appended to the default LLM system prompt for all users in this organisation.'),
        ),
    ]
