# Generated by Django 5.1.1 on 2026-07-23 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_coreorganisation_org_prompt'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='memory',
            options={'permissions': [('write_org_memory', 'Can write organisation-wide memories')], 'verbose_name': 'Memory', 'verbose_name_plural': 'Memories'},
        ),
    ]
