# Generated by Django 5.2.12 on 2026-07-25 03:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_alter_memory_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeasuredRelationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overlap_ratio', models.FloatField(help_text="Fraction of the smaller side's distinct values also present in the other side.")),
                ('smaller_domain_size', models.BigIntegerField(help_text='Distinct value count of the smaller-cardinality side (the cardinality-gate input).')),
                ('smaller_distinct_ratio', models.FloatField(help_text="The smaller side's distinct/row ratio WITHIN ITS OWN TABLE. Gate on this (repetition), not on raw domain size — a genuine key on a small table is not a trap.")),
                ('verdict', models.CharField(choices=[('reliable', 'Reliable'), ('partial', 'Partial'), ('suspicious', 'Suspicious'), ('low_cardinality_trap', 'Low-cardinality trap')], max_length=24)),
                ('cardinality', models.CharField(blank=True, choices=[('one_to_one', 'One to one'), ('one_to_many', 'One to many'), ('many_to_one', 'Many to one'), ('many_to_many', 'Many to many')], max_length=16, null=True)),
                ('orphan_count', models.BigIntegerField(blank=True, help_text='Distinct many-side values with no match on the other side (inner-join drops them).', null=True)),
                ('composite_key_members', models.JSONField(blank=True, default=list, help_text='TableColumn ids needed to form a real join when this edge alone is a low_cardinality_trap (e.g. the high-cardinality partner in a composite key).')),
                ('provenance', models.CharField(choices=[('declared', 'Declared (source FK)'), ('measured', 'Measured from data'), ('human_asserted', 'Human asserted')], default='measured', max_length=16)),
                ('confidence', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', max_length=8)),
                ('is_protected', models.BooleanField(default=False, help_text='Human-asserted edges are not silently overwritten by re-measurement; a contradicting measurement is surfaced for review instead.')),
                ('content_hash', models.CharField(blank=True, help_text='Hash of the material fields; drives change-gating so an unchanged re-run only bumps last_confirmed_at instead of recording churn.', max_length=64)),
                ('first_discovered_at', models.DateTimeField(auto_now_add=True)),
                ('last_confirmed_at', models.DateTimeField(auto_now=True, help_text='Bumped on every discovery run (cheap).')),
                ('last_changed_at', models.DateTimeField(blank=True, help_text='Moves only when content_hash materially changes.', null=True)),
                ('data_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='measured_relationships', to='core.datasource')),
                ('from_column', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='measured_rel_from', to='core.tablecolumn')),
                ('to_column', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='measured_rel_to', to='core.tablecolumn')),
            ],
            options={
                'db_table': 'terno_measuredrelationship',
                'indexes': [models.Index(fields=['data_source', 'from_column'], name='terno_measu_data_so_c190d9_idx'), models.Index(fields=['data_source', 'to_column'], name='terno_measu_data_so_3045bf_idx')],
                'constraints': [models.UniqueConstraint(fields=('from_column', 'to_column'), name='uniq_measured_relationship_edge')],
            },
        ),
    ]
