# Generated by Django 5.2.12 on 2026-08-11 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_alter_memory_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicetoken',
            name='token_type',
            field=models.CharField(choices=[('admin', 'Admin Service'), ('query', 'Query Service'), ('oauth', 'OAuth Connector')], default='query', max_length=10),
        ),
    ]
