# Generated by Django 5.2.12 on 2026-07-25 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_measuredrelationship'),
    ]

    operations = [
        migrations.AddField(
            model_name='measuredrelationship',
            name='rollup_evidence',
            field=models.TextField(blank=True, help_text='D5: which measure column, row-count comparison, and monotonicity sample result produced the rollup_signal — the evidence, not just the verdict.'),
        ),
        migrations.AddField(
            model_name='measuredrelationship',
            name='rollup_signal',
            field=models.CharField(choices=[('none', 'Not a rollup pair'), ('to_is_rollup', '`to` side is the authoritative summary'), ('from_is_rollup', '`from` side is the authoritative summary'), ('uncertain', 'Looks like a rollup pair but direction unclear')], default='none', help_text='D5: set when the two tables share an entity key AND a same-named numeric measure, with a row-count/monotonicity pattern suggesting one side is a precomputed summary of the other.', max_length=16),
        ),
    ]
