# Generated by Django 5.1.1 on 2026-09-07 04:59

import terno_dbi.core.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_servicetoken_oauth_token_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasource',
            name='connection_json',
            field=terno_dbi.core.fields.EncryptedJSONField(blank=True, help_text='JSON key file contents for authentication.<br><br><b>Examples:</b><br>&bull; <b>BigQuery:</b> Paste the entire contents of your Google Cloud Service Account JSON key file here.', null=True),
        ),
        migrations.AlterField(
            model_name='datasource',
            name='connection_str',
            field=terno_dbi.core.fields.EncryptedTextField(help_text='Connection string for the datasource.<br><br><b>Examples:</b><br>&bull; <b>Postgres:</b> <code>postgresql://user:password@host:port/dbname</code><br>&bull; <b>MySQL:</b> <code>mysql+pymysql://user:password@host:port/dbname</code><br>&bull; <b>Oracle:</b> <code>oracle+oracledb://user:password@host:port/?service_name=service_name</code><br>&bull; <b>Snowflake:</b> <code>snowflake://user:password@account_identifier/dbname/schema_name?warehouse=warehouse_name</code><br>&bull; <b>BigQuery:</b> <code>bigquery://project_id/dataset_id</code> <i>(Requires Connection JSON)</i><br>&bull; <b>DataBricks:</b> <code>databricks://token:dapi_token@host:port?http_path=/sql/1.0/endpoints/12345</code>'),
        ),
    ]
