# Generated by Django 5.1.1 on 2026-09-07 11:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('core', '0025_encrypt_datasource_credentials'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConnectorCatalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(max_length=64, unique=True)),
                ('enabled', models.BooleanField(default=True, help_text='Turn a source off for this deployment. A catalog refresh never changes this.')),
                ('sort_order', models.IntegerField(default=100)),
                ('most_popular', models.BooleanField(default=False)),
                ('display_name_override', models.CharField(blank=True, default='', max_length=80)),
                ('description_override', models.TextField(blank=True, default='')),
                ('display_name', models.CharField(max_length=80)),
                ('provider', models.CharField(blank=True, default='', max_length=60)),
                ('category', models.CharField(blank=True, default='', max_length=40)),
                ('description', models.TextField(blank=True, default='')),
                ('icon_url', models.URLField(blank=True, default='')),
                ('scopes_label', models.CharField(blank=True, default='', max_length=200)),
                ('family', models.CharField(choices=[('database', 'Database'), ('api', 'API')], max_length=16)),
                ('auth_type', models.CharField(choices=[('oauth', 'OAuth'), ('manual', 'Credentials')], max_length=16)),
                ('fields_spec', models.JSONField(blank=True, default=list)),
                ('has_account_list', models.BooleanField(default=False)),
                ('has_fields', models.BooleanField(default=False)),
                ('has_report_types', models.BooleanField(default=False)),
                ('is_date_range_required', models.BooleanField(default=False)),
                ('report_types', models.JSONField(blank=True, default=list)),
                ('default_report_type', models.CharField(blank=True, default='', max_length=64)),
                ('account_label_singular', models.CharField(default='Account', max_length=40)),
                ('account_label_plural', models.CharField(default='Accounts', max_length=40)),
            ],
            options={
                'verbose_name_plural': 'Connector catalog',
                'db_table': 'terno_connector_catalog',
                'ordering': ('sort_order', 'display_name'),
            },
        ),
        migrations.AddField(
            model_name='datasource',
            name='auth_error',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='datasource',
            name='auth_status',
            field=models.CharField(choices=[('not_authenticated', 'Not authenticated'), ('connected', 'Connected'), ('expired', 'Needs reconnect'), ('error', 'Error')], default='connected', help_text='Whether this connection can currently reach its source.', max_length=32),
        ),
        migrations.AddField(
            model_name='datasource',
            name='last_synced',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='datasource',
            name='catalog',
            field=models.ForeignKey(blank=True, help_text="Which catalog entry this connection is an instance of. PROTECT, not CASCADE — retiring a catalog entry must never silently delete a customer's configured datasource.", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='datasources', to='core.connectorcatalog'),
        ),
        migrations.CreateModel(
            name='ApiQueryJob',
            fields=[
                ('id', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=16)),
                ('spec', models.JSONField(default=dict)),
                ('result', models.JSONField(blank=True, null=True)),
                ('error', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('data_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_query_jobs', to='core.datasource')),
                ('organisation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='api_query_jobs', to='core.coreorganisation')),
            ],
            options={
                'db_table': 'terno_api_query_job',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['organisation', 'status'], name='terno_api_q_organis_ca56fc_idx')],
            },
        ),
        migrations.CreateModel(
            name='ConnectorOAuthState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(db_index=True, max_length=128, unique=True)),
                ('connector_key', models.CharField(max_length=64)),
                ('code_verifier', models.CharField(blank=True, default='', max_length=128)),
                ('redirect_uri', models.CharField(max_length=500)),
                ('return_to', models.CharField(blank=True, default='', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('data_source', models.ForeignKey(blank=True, help_text='Set when reconnecting an existing datasource; null on first connect.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='oauth_states', to='core.datasource')),
                ('organisation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='connector_oauth_states', to='core.coreorganisation')),
            ],
            options={
                'db_table': 'terno_connector_oauth_state',
                'indexes': [models.Index(fields=['expires_at'], name='terno_conne_expires_909fb1_idx')],
            },
        ),
        migrations.CreateModel(
            name='GroupAccountAllowlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_id', models.CharField(max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('data_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_allowlists', to='core.datasource')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_allowlists', to='auth.group')),
            ],
            options={
                'db_table': 'terno_group_account_allowlist',
                'indexes': [models.Index(fields=['data_source'], name='terno_group_data_so_ebfcce_idx')],
                'constraints': [models.UniqueConstraint(fields=('group', 'data_source', 'account_id'), name='uniq_group_datasource_account')],
            },
        ),
    ]
