# Generated by Django 5.1.1 on 2026-09-09 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_seed_and_attach_catalog'),
    ]

    operations = [
        migrations.AddField(
            model_name='connectorcatalog',
            name='rate_limit_per_day',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='connectorcatalog',
            name='rate_limit_per_second',
            field=models.IntegerField(default=0),
        ),
    ]
