# Generated by Django 5.1.1 on 2026-09-10 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_connectorcatalog_rate_limit_per_day_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasource',
            name='type',
            field=models.CharField(choices=[('generic', 'Generic'), ('oracle', 'Oracle'), ('mysql', 'MySQL'), ('postgres', 'Postgres'), ('bigquery', 'BigQuery'), ('databricks', 'DataBricks'), ('snowflake', 'Snowflake')], default='generic', max_length=64),
        ),
    ]
