# Generated by Django 5.1.1 on 2026-09-21 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_alter_datasource_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='connectoroauthstate',
            name='instance',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
