# Generated by Django 5.1.1 on 2026-09-24 03:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_connectoroauthstate_instance'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConnectorAccountSelection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_id', models.CharField(max_length=255)),
                ('account_name', models.CharField(blank=True, max_length=255)),
                ('enabled', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('data_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_selections', to='core.datasource')),
            ],
            options={
                'db_table': 'terno_connector_account_selection',
                'indexes': [models.Index(fields=['data_source'], name='terno_conne_data_so_2824eb_idx')],
                'constraints': [models.UniqueConstraint(fields=('data_source', 'account_id'), name='uniq_datasource_account_selection')],
            },
        ),
    ]
