# Generated by Django 5.1.1 on 2026-09-25 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_connectoraccountselection'),
    ]

    operations = [
        migrations.AddField(
            model_name='connectoraccountselection',
            name='writes_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
