# Generated by Django 5.1.1 on 2026-09-25 12:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_connectoraccountselection_writes_enabled'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConnectorWriteLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_name', models.CharField(blank=True, max_length=255)),
                ('connector_key', models.CharField(blank=True, max_length=100)),
                ('account_id', models.CharField(max_length=255)),
                ('action', models.CharField(max_length=100)),
                ('params', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('success', 'Success'), ('error', 'Error')], default='success', max_length=16)),
                ('summary', models.CharField(blank=True, max_length=500)),
                ('before', models.JSONField(blank=True, null=True)),
                ('after', models.JSONField(blank=True, null=True)),
                ('error_code', models.CharField(blank=True, max_length=64)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='connector_write_logs', to=settings.AUTH_USER_MODEL)),
                ('data_source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='write_logs', to='core.datasource')),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connector_write_logs', to='core.coreorganisation')),
            ],
            options={
                'db_table': 'terno_connector_write_log',
                'indexes': [models.Index(fields=['organisation', '-created_at'], name='terno_conne_organis_e704ce_idx'), models.Index(fields=['data_source', '-created_at'], name='terno_conne_data_so_2479ec_idx')],
            },
        ),
    ]
