# Generated by Django 5.1.1 on 2026-09-29 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_connectorwritelog'),
    ]

    operations = [
        migrations.AddField(
            model_name='connectoraccountselection',
            name='manager_id',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
