# Generated by Django 5.1.1 on 2026-09-29 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_connectoraccountselection_manager_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='connectoraccountselection',
            name='manager_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
