# Generated by Django 5.1.1 on 2026-10-05 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_connectoraccountselection_manager_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='connectoroauthstate',
            name='login_method',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
    ]
