# Generated by Django 5.2.12 on 2026-10-08 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_connectoroauthstate_login_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='coreorganisation',
            name='provisioning_key',
            field=models.CharField(blank=True, help_text='Stable key an external provisioner uses to create this org idempotently; null for orgs not created that way.', max_length=255, null=True, unique=True),
        ),
    ]
